### ISSUE TITLE
Dupes of certain blocks when broken

### ISSUE THREAD

**Issue by jinkhya** [HurtsAsHell/Not-Sky-Industry-Public#2]
The singularity tanks and bonsai pots get duped when broken. (the bonsai one even dupes the soil and the sapling).
It's caused by multi mine mod.
https://github.com/thraaawn/BonsaiTrees/issues/123

**Comment by HurtsAsHell** [comment]
I think that was a bug of bonsaipot, i will check asap

**Comment by jinkhya** [comment]
I tried disabling that mod on our servers and both dupes got fixed.

**Comment by ItHurtsLikeHell** [comment]
This is fixed, i've removed Multi-Mine
