### ISSUE TITLE
Recipe conflict between obsidian pillar from cathedral and rods from obsidian rods from more rods mod

### ISSUE THREAD

**Issue by jinkhya** [HurtsAsHell/Not-Sky-Industry-Public#3]
https://i.imgur.com/DXYPqob.png
https://i.imgur.com/cxIJq96.png

You can only get the cathedral one atm, the rod is more important, it's in 2 custom recipes.

**Comment by ItHurtsLikeHell** [comment]
hey, thanks for the report.
Actually i'm not at home and i can't solve this problem but i know it, i've reported it in Discord.

**Comment by jinkhya** [comment]
no worries, I added an horizontal recipe as a temp fix for the rod so my friend can get the rod. :)
https://i.imgur.com/Xv4H8Y7.png

**Comment by ItHurtsLikeHell** [comment]
Good, and soory for the inconvenience.
I haven't a good portable pc so i can't do nothing, srry.
