### ISSUE TITLE
Charged Certus quartz texture bugged

### ISSUE THREAD

**Issue by jinkhya** [HurtsAsHell/Not-Sky-Industry-Public#4]
The charged certus ore is looking a bit weird. It still gives you the right drops when you break it. The normal certus ore has the proper texture.

https://i.imgur.com/OWsBnxG.png

**Comment by ItHurtsLikeHell** [comment]
https://www.reddit.com/r/feedthebeast/comments/9h92bh/i_like_the_new_texture_for_charged_certus_ore/ 🤣

**Comment by ItHurtsLikeHell** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3905

This issues is closed but it tell that the problem is related to Optifine.

Chisel don't cause this problem so i need to see the log and test something

**Comment by jinkhya** [comment]
After trying a few things : 
AE2 + betterwithmods + CTM ==> bug
AE2 + CTM ==> no bug
AE2 + betterwithmods --> no bug

AE2+betterwithmods+CTM+optifine ==> no bug

**Comment by ItHurtsLikeHell** [comment]
So i need to add optifine, lol.
Thanks to help

**Comment by HurtsAsHell** [comment]
I can't add Optifine to modpack because isn't in Curseforge so, i'll pin this issues
