### ISSUE TITLE
Dupe soulus and Carryon

### ISSUE THREAD

**Issue by jinkhya** [HurtsAsHell/Not-Sky-Industry-Public#5]
When picking up a Soulus spawner that has an essence book in it, using Carryon on it will dupe the spawner and the book. If upgrades were attached, they also get duped.

**Comment by ItHurtsLikeHell** [comment]
Yes I know it and i think that I couldn't fix it and I don't want fix it because it's a little "help" to player.
If player don't like that could destroy the second spawner

**Comment by jinkhya** [comment]
You could add soulus:summoner to forbiddenTiles in carryon.cfg. Crafted soulus spawners can be broken with pickaxes, and if you want to pick up spawner from nether you can use the moving wand (moving wand doesn't dupe).
