### ISSUE TITLE
Enchantment table and brewing stand disabled

### ISSUE THREAD

**Issue by jinkhya** [HurtsAsHell/Not-Sky-Industry-Public#6]
I believe Betterwithmods disabled those : 

    # Makes it so structures are looted within a radius of spawn and unlooted outside of that radius. Encourages exploration and also makes unlooted structures the only source of Enchanting Tables and Brewing Stands.
    B:HCStructures=true

About the Enchantment table, I know there's the lapis stays in enchantment table one but a few recipes need the vanilla one. 

About the brewing stand, it's used in the Industrial Foregoing potion brewer recipe so there's no way, to my knowledge, to make vanilla potions. I thought about going to the end, to find some in endcities, but I didn't find any structures in the end, the structures seem to be disabled in the end.

**Comment by HurtsAsHell** [comment]
Enchantment table crafting fixed.
Structure are disabled in the overworld but in the end and in the nether, are structure and mob spawner.
Could be that in the nether aren't villages.
I don't want that the player could craft the vanilla potion, i hate vanilla and this is a modpack so you could use the industiral foregoind potion that craft vanilla potion too or use the Drink that give you some effects.

Anyway I'll try to disable the config.

**Comment by jinkhya** [comment]
There's no structure in the end. /locate command tells you coordinates of endcities but when you teleport there, there's nothing.

I'm fine with using the industrial foregoing brewer but that recipe uses a vanilla brewer. 
I only want potions to be able to craft the magneticraft water generator :)

**Comment by HurtsAsHell** [comment]
the "potion" could be an Awkward Potion

**Comment by HurtsAsHell** [comment]
![Cattura](https://user-images.githubusercontent.com/37914234/71783182-58ac7400-2fe3-11ea-8484-43a4946f16fb.PNG)

**Comment by HurtsAsHell** [comment]
I've added a crafting for IE Brewer, please open other issues for the ender cities
