### ISSUE TITLE
Glass dupe from crafting fish tank

### ISSUE THREAD

**Issue by featsuperior94** [HurtsAsHell/Not-Sky-Industry-Public#7]
i was crafting fish tanks and when crafted it duplicates the glass. as you can see got 126 glass in each stack from this glitch
![fist tank dupe](https://user-images.githubusercontent.com/51495376/71745571-7d181d00-2e38-11ea-804f-3daedd876dfe.PNG)

**Comment by ItHurtsLikeHell** [comment]
wtf? ahahha

**Comment by featsuperior94** [comment]
i know idk how but it gave me stacks of glass lol

**Comment by HurtsAsHell** [comment]
I'm looking but i can't fix this issues :/
